const products = [
  {
    id: 0,
    name: "Bikini with connectors C/D cup Bottom Small",
    price: 2000,
    instock: 100,
    description: "Color fade with gold navy and black crystals",
    imgSrc: "./img/bikinis/img7.jpg",
  },
  {
    id: 1,
    name: "Russian Bikini C/D cup Bottom Small",
    price: 1900,
    instock: 43,
    description: "Color fade with 4 shades of blue crystals",
    imgSrc: "./img/bikinis/img9.jpg",
  },
  {
    id: 2,
    name: "Russian Practice Bikini C cup Bottom small",
    price: 1500,
    instock: 10,
    description: "Purple Velvet",
    imgSrc: "./img/bikinis/img11.jpg",
  },
  {
    id: 3,
    name: "Bikini with connectors C cup Bottom Small",
    price: 1900,
    instock: 5,
    description: "Color fade with 2 shades of red and AB crystals",
    imgSrc: "./img/bikinis/img13.jpg",
  },
  {
    id: 4,
    name: "Bikini with connectors C/D cup Bottom Small",
    price: 1900,
    instock: 4,
    description: "Color fade with 4 shades of green crystals",
    imgSrc: "./img/bikinis/img15.jpg",
  },
  {
    id: 5,
    name: "Bikini with connectors C/D cup Bottom Small",
    price: 1900,
    instock: 40,
    description: "Color fade with 3 shades of purple and pink crystals",
    imgSrc: "./img/bikinis/img44.jpg",
  },
  {
    id: 6,
    name: "Russian Bikini D cup Bottom medium",
    price: 1900,
    instock: 40,
    description: "Color crystals in red pink and neon pink",
    imgSrc: "./img/bikinis/img46.jpg",
  },
  {
    id: 7,
    name: "Russian Bikini C/D cup Bottom small",
    price: 1900,
    instock: 40,
    description: "Color fade in orange red pink and purple crystals.",
    imgSrc: "./img/bikinis/img48.jpg",
  },
  {
    id: 8,
    name: "Russian Bikini C cup Bottom small",
    price: 1900,
    instock: 40,
    description: "Color fade in black, gold and fire crystals",
    imgSrc: "./img/bikinis/img50.jpg",
  },
  {
    id: 9,
    name: "Russian Bikini D cup Bottom small",
    price: 1700,
    instock: 40,
    description: "Color fade in blue, purple aquamarine and pink crystals",
    imgSrc: "./img/bikinis/img52.jpg",
  },
  {
    id: 10,
    name: "Gala",
    price: 900,
    instock: 40,
    description: "sizes: 35-36-37-38-39-40-41-42",
    imgSrc: "./img/shoes/img78.jpg",
  },
  {
    id: 11,
    name: "Flair",
    price: 950,
    instock: 40,
    description: "sizes: 35-36-37-38-39-40-41-42",
    imgSrc: "./img/shoes/img79.jpg",
  },
  {
    id: 12,
    name: "Lip",
    price: 975,
    instock: 40,
    description: "sizes: 35-36-37-38-39-40-41-42",
    imgSrc: "./img/shoes/img80.jpg",
  },
  {
    id: 13,
    name: "Lip",
    price: 1400,
    instock: 40,
    description: "sizes: 35-36-37-38-39-40-41-42",
    imgSrc: "./img/shoes/img81.jpg",
  },
  {
    id: 14,
    name: "Custom",
    price: 1400,
    instock: 40,
    description: "sizes: 35-36-37-38-39-40-41-42",
    imgSrc: "./img/shoes/img82.jpg",
  },
  // {
  //   id: 5,
  //   name: "T-shirt 6",
  //   price: 39.99,
  //   instock: 40,
  //   description:
  //     "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
  //   imgSrc: "./img/t6.png",
  // },
  // {
  //   id: 5,
  //   name: "T-shirt 6",
  //   price: 39.99,
  //   instock: 40,
  //   description:
  //     "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
  //   imgSrc: "./img/t6.png",
  // },
  // {
  //   id: 5,
  //   name: "T-shirt 6",
  //   price: 39.99,
  //   instock: 40,
  //   description:
  //     "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
  //   imgSrc: "./img/t6.png",
  // },
  // {
  //   id: 5,
  //   name: "T-shirt 6",
  //   price: 39.99,
  //   instock: 40,
  //   description:
  //     "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
  //   imgSrc: "./img/t6.png",
  // },
  // {
  //   id: 5,
  //   name: "T-shirt 6",
  //   price: 39.99,
  //   instock: 40,
  //   description:
  //     "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
  //   imgSrc: "./img/t6.png",
  // },
];
